# Generated by Django 4.2 on 2023-04-27 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_uploading',
            name='date_posted',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 27)),
        ),
        migrations.AddField(
            model_name='notice_uploading',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
